services:
  couchdb-obsidian-livesync:
    container_name: obsidian-livesync
    image: couchdb
    environment:
      - PUID=1000
      - PGID=100
      - COUCHDB_USER=obsidian_user
      - COUCHDB_PASSWORD=movetosoap
    volumes:
      - ./data:/opt/couchdb/data
      - ./etc/local.d:/opt/couchdb/etc/local.d
    ports:
      - "5984:5984"
    restart: unless-stopped
