services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3002:8080"
    environment:
      - OLLAMA_BASE_URL=http://10.100.0.3:11434
    volumes:
      - open-webui:/app/backend/data

      
volumes:  # Define the named volume here
  open-webui:
