networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
services:
  ha:
    container_name: ha
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /run/dbus:/run/dbus:ro
      - ./ha:/config
      - ./media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
  esphome:
    image: ghcr.io/imagegenius/esphome:latest
    container_name: esphome
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - ./esphome:/config
    ports:
      - 6052:6052
    restart: unless-stopped
